global:
  qsname: quickstart-microsoft-sharepoint
  reporting: true
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  quickstart-microsoft-sharepointt1:
    template_file: quickstart-microsoft-sharepoint-example1.template
    parameter_input: quickstart-microsoft-sharepoint-exampleparms1.json
  quickstart-microsoft-sharepointt2:
    template_file: quickstart-microsoft-sharepoint-example2.template
    parameter_input: quickstart-microsoft-sharepoint-exampleparms2.json
